-- ============================================================================
-- Chain of Verification (CoVe) Project - Table Definitions
-- ============================================================================

USE DATABASE COVE_PROJECT_DB;

-- ============================================================================
-- RAW_DATA Schema - Source Tables
-- ============================================================================

USE SCHEMA RAW_DATA;

-- Products Table
CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID VARCHAR(50) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    CATEGORY VARCHAR(100),
    SUBCATEGORY VARCHAR(100),
    PRICE DECIMAL(10, 2),
    COST DECIMAL(10, 2),
    STOCK_QUANTITY INT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Customers Table
CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID VARCHAR(50) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    PHONE VARCHAR(50),
    SEGMENT VARCHAR(50),  -- Enterprise, SMB, Consumer
    REGION VARCHAR(100),
    COUNTRY VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LIFETIME_VALUE DECIMAL(12, 2) DEFAULT 0
);

-- Orders Table
CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID VARCHAR(50) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(50) REFERENCES CUSTOMERS(CUSTOMER_ID),
    PRODUCT_ID VARCHAR(50) REFERENCES PRODUCTS(PRODUCT_ID),
    QUANTITY INT NOT NULL,
    UNIT_PRICE DECIMAL(10, 2) NOT NULL,
    AMOUNT DECIMAL(12, 2) NOT NULL,  -- quantity * unit_price
    DISCOUNT_PERCENT DECIMAL(5, 2) DEFAULT 0,
    ORDER_DATE DATE NOT NULL,
    ORDER_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUS VARCHAR(50) DEFAULT 'completed',  -- pending, completed, cancelled, refunded
    QUARTER VARCHAR(10)  -- Q1-2024, Q2-2024, etc.
);

-- Support Tickets Table
CREATE OR REPLACE TABLE SUPPORT_TICKETS (
    TICKET_ID VARCHAR(50) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(50) REFERENCES CUSTOMERS(CUSTOMER_ID),
    ISSUE TEXT NOT NULL,
    ISSUE_CATEGORY VARCHAR(100),
    PRIORITY VARCHAR(20),  -- low, medium, high, critical
    RESOLUTION TEXT,
    STATUS VARCHAR(50) DEFAULT 'open',  -- open, in_progress, resolved, closed
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RESOLVED_AT TIMESTAMP_NTZ,
    SATISFACTION_SCORE INT  -- 1-5
);

-- Knowledge Base Table (for Cortex Search RAG)
CREATE OR REPLACE TABLE KNOWLEDGE_BASE (
    DOC_ID VARCHAR(50) PRIMARY KEY,
    TITLE VARCHAR(500) NOT NULL,
    CONTENT TEXT NOT NULL,
    CATEGORY VARCHAR(100),
    SUBCATEGORY VARCHAR(100),
    TAGS ARRAY,
    SOURCE VARCHAR(100),  -- manual, api_docs, faq, policy
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    VERSION INT DEFAULT 1
);

-- ============================================================================
-- ANALYTICS Schema - Aggregated Tables
-- ============================================================================

USE SCHEMA ANALYTICS;

-- Daily Sales Metrics
CREATE OR REPLACE TABLE DAILY_SALES_METRICS (
    DATE DATE PRIMARY KEY,
    TOTAL_REVENUE DECIMAL(15, 2),
    ORDER_COUNT INT,
    AVG_ORDER_VALUE DECIMAL(10, 2),
    UNIQUE_CUSTOMERS INT,
    UNITS_SOLD INT,
    REFUND_AMOUNT DECIMAL(12, 2) DEFAULT 0,
    NET_REVENUE DECIMAL(15, 2)
);

-- Customer Segments
CREATE OR REPLACE TABLE CUSTOMER_SEGMENTS (
    SEGMENT_ID VARCHAR(50) PRIMARY KEY,
    SEGMENT_NAME VARCHAR(100) NOT NULL,
    CUSTOMER_COUNT INT,
    TOTAL_LTV DECIMAL(15, 2),
    AVG_LTV DECIMAL(12, 2),
    TOTAL_ORDERS INT,
    AVG_ORDER_VALUE DECIMAL(10, 2),
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Product Performance
CREATE OR REPLACE TABLE PRODUCT_PERFORMANCE (
    PRODUCT_ID VARCHAR(50) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255),
    CATEGORY VARCHAR(100),
    UNITS_SOLD INT,
    REVENUE DECIMAL(15, 2),
    RETURN_RATE DECIMAL(5, 2),
    AVG_RATING DECIMAL(3, 2),
    REVIEW_COUNT INT,
    PERIOD VARCHAR(20),  -- monthly, quarterly, yearly
    PERIOD_VALUE VARCHAR(20)  -- 2024-01, Q4-2024, 2024
);

-- ============================================================================
-- COVE_LOGS Schema - Audit Trail
-- ============================================================================

USE SCHEMA COVE_LOGS;

-- Verification Runs
CREATE OR REPLACE TABLE VERIFICATION_RUNS (
    RUN_ID VARCHAR(50) PRIMARY KEY,
    USER_QUERY TEXT NOT NULL,
    BASELINE_RESPONSE TEXT,
    VERIFIED_RESPONSE TEXT,
    MODEL_USED VARCHAR(100),
    TOTAL_VQ_COUNT INT,
    CONSISTENT_COUNT INT,
    INCONSISTENT_COUNT INT,
    EXECUTION_TIME_MS INT,
    STATUS VARCHAR(50),  -- success, partial, failed
    ERROR_MESSAGE TEXT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Verification Questions
CREATE OR REPLACE TABLE VERIFICATION_QUESTIONS (
    VQ_ID VARCHAR(50) PRIMARY KEY,
    RUN_ID VARCHAR(50) REFERENCES VERIFICATION_RUNS(RUN_ID),
    FACT_CLAIM TEXT NOT NULL,
    VERIFICATION_QUESTION TEXT NOT NULL,
    ANSWER TEXT,
    SOURCE VARCHAR(50),  -- cortex_analyst, cortex_search, llm
    SOURCE_DETAIL TEXT,  -- SQL query or search query used
    IS_CONSISTENT BOOLEAN,
    CONFIDENCE_SCORE DECIMAL(3, 2),
    EXECUTION_TIME_MS INT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create indexes for better query performance
CREATE OR REPLACE INDEX idx_vq_run_id ON VERIFICATION_QUESTIONS(RUN_ID);
CREATE OR REPLACE INDEX idx_runs_created ON VERIFICATION_RUNS(CREATED_AT);
